### ISSUE TITLE
Links in 'Contact' page

### ISSUE THREAD

**Issue by shineyruan** [ve450su2020-group23/Frontend#15]
I see that in our website each name in the 'Contact' page (e.g., 'Zhihao Ruan') has its individual link. However, for now all the links are just pointing towards the top of the page. I assume that these links are originally meant to point to each member's personal website/social media/GitHub home page, etc. Am I correct?

Also I propose that 'Group23' should link to our GitHub organization home page, which is https://github.com/ve450su2020-group23. 

The links of our sponsors and instructors can be made to point to their introduction page in the 'faculty' or 'staff' section on JI's official website. Or at least we should ask for their preferences.

**Comment by shineyruan** [comment]
For my individual name please link it to my personal website: https://zhihaoruan.xyz/

**Comment by kzlkz** [comment]
That could be one good way to use this! Another way may be triggering a new mail to the member's email.

**Comment by kzlkz** [comment]
Link set to github page (Ryan: personal page).
