### ISSUE TITLE
Project deliverables on website

### ISSUE THREAD

**Issue by shineyruan** [ve450su2020-group23/Frontend#17]
In our website there are two final deliverables: 'People counting system with single human-defined entrance' and 'People counting system with automatic entrances detection and separated counting'. However, in `object-tracking`'s actual implementation, these two features are exclusive modes that cannot run at the same time. The default would only be automatic entrances detection and separated counting.

In addition, in the 2nd final deliverable, I see no design of displaying `in`s and `out`s for multiple entrances at the same time. From the Raspberry Pi's end there should be a `json` file that documents each `in` and each `out` for each individual entrance. Would be nice if this display option can be added neatly.

**Comment by kzlkz** [comment]
There is a Option component to select which entrance's data you want to see on the chart, do you mean a feature putting all in's and out's in the same one chart?

**Comment by kzlkz** [comment]
I guess it is discussable whether deliverable 1 is necessary on the demo page.

**Comment by shineyruan** [comment]
> There is a Option component to select which entrance's data you want to see on the chart, do you mean a feature putting all in's and out's in the same one chart?

Oh I see. An option button will also do!
