### ISSUE TITLE
视频智能跳转/搜索功能

### ISSUE THREAD

**Issue by kzlkz** [ve450su2020-group23/Frontend#21]
1. 给定timestamp 跳转
2. 给定时间跳转

**Comment by shineyruan** [comment]
我觉得这个功能可以扩展为一个通用的搜索的功能。我觉得不仅是视频搜索，数据也可以做一个根据输入的时间点自动搜索出对应的时间段数据的功能，等等

比如说我输入7/31/2020 12:42 PM，能搜索出12:35 -- 12:45这个时间段的数据并展示相对应的图表，视频，等等。

以及一键跳转到latest video的功能

**Comment by kzlkz** [comment]
> 我觉得这个功能可以扩展为一个通用的搜索的功能。我觉得不仅是视频搜索，数据也可以做一个根据输入的时间点自动搜索出对应的时间段数据的功能，等等
> 
> 比如说我输入7/31/2020 12:42 PM，能搜索出12:35 -- 12:45这个时间段的数据并展示相对应的图表，视频，等等。

可以，相当于我自动取一个附近的时间段？能复用现在的逻辑

**Comment by shineyruan** [comment]
> > 我觉得这个功能可以扩展为一个通用的搜索的功能。我觉得不仅是视频搜索，数据也可以做一个根据输入的时间点自动搜索出对应的时间段数据的功能，等等
> > 比如说我输入7/31/2020 12:42 PM，能搜索出12:35 -- 12:45这个时间段的数据并展示相对应的图表，视频，等等。
> 
> 可以，相当于我自动取一个附近的时间段？能复用现在的逻辑

Exactly yes

**Comment by kzlkz** [comment]
Features added.
